version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.7.0
         environment:
           RAILS_ENV: test
           PGHOST: 127.0.0.1
           PGUSER: circleci
       - image: circleci/postgres:10.4-alpine
         environment:
           POSTGRES_USER: circleci
           POSTGRES_DB: sokuseki_test

    working_directory: ~/myapp
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}
          - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: rubocop
          command: bundle exec rubocop

      - run:
          name: Database Setup
          command: bundle exec rake db:setup

      - run:
          name: rspec
          command: bundle exec rspec
