openapi: 3.0.2
info:
  title: Sokuseki API
  version: 0.0.1
servers:
  - url: http://localhost:3000
    description: development
paths:
  /people:
    $ref: "./paths/people.yml"
components:
  schemas:
    PeopleProperties:
      $ref: "./components/schemas/peopleProperties.yml"
